Jenkins pipelines: adding stages to Provision and Destroy EC2 Infra. Terraform: adding EC2 infra resources

diff --git a/Jenkinsfile.destroy b/Jenkinsfile.destroy
--- a/Jenkinsfile.destroy
+++ b/Jenkinsfile.destroy
@@ -2,15 +2,47 @@ pipeline {
   agent any
 
   environment {
-    TF_ECR_SSM_DIR = 'terraform/ecr_ssm'
     AWS_REGION     = 'us-east-1'
     ECR_REPO       = 'weather-service'
+    ACCOUNT_ID     = '061039805700'
+
+    TF_ECR_SSM_DIR = 'terraform/ecr_ssm'
+    TF_INFRA_DIR   = 'terraform/infra'
   }
 
   stages {
     stage('Checkout') {
       steps {
         checkout scm
+      }
+    }
+
+    stage('Destroy EC2 Infrastructure') {
+      steps {
+        dir("${TF_INFRA_DIR}") {
+          withCredentials([
+            string(credentialsId: 'aws-access-key', variable: 'AWS_ACCESS_KEY_ID'),
+            string(credentialsId: 'aws-secret-key', variable: 'AWS_SECRET_ACCESS_KEY')
+          ]) {
+            sh """
+              set -e
+              terraform init -input=false
+              terraform destroy -auto-approve \
+                -var='aws_region=${AWS_REGION}' \
+                -var='account_id=${ACCOUNT_ID}' \
+                -var='image_tag=${IMAGE_TAG}' \
+                -var='instance_type=t2.micro'
+            """
+          }
+        }
+      }
+      post {
+        failure {
+          echo "❌ Failed to destroy EC2 infra"
+        }
+        success {
+          echo "✅ EC2 infra destroyed"
+        }
       }
     }
 
